import { useState } from "react";
import { ShieldCheck, X } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

export function ResponsibleAiBanner() {
  const [open, setOpen] = useState(false);

  return (
    <>
      <div className="fixed inset-x-0 top-0 z-50 flex h-9 items-center justify-between gap-4 border-b border-border bg-banner px-4 sm:px-6">
        <div className="flex min-w-0 items-center gap-3">
          <span className="relative flex size-2 shrink-0">
            <span className="absolute inline-flex size-full animate-ping rounded-full bg-signal opacity-60" />
            <span className="relative inline-flex size-2 rounded-full bg-signal" />
          </span>
          <span className="label-mono truncate text-banner-foreground">
            Responsible AI Protocol Active &bull; v2.4.0
          </span>
        </div>
        <div className="flex items-center gap-4">
          <span className="hidden text-[11px] italic text-banner-foreground md:inline">
            Outputs are AI-generated and require verification.
          </span>
          <button
            onClick={() => setOpen(true)}
            className="text-[11px] font-semibold text-foreground hover:underline"
          >
            Learn More
          </button>
        </div>
      </div>

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2 text-base">
              <ShieldCheck className="size-4 text-signal" />
              Responsible AI in TaskFlow
            </DialogTitle>
            <DialogDescription className="pt-2 text-sm leading-relaxed">
              Every summary, draft, plan, and answer in TaskFlow is generated by a language model and
              may contain errors or omissions.
            </DialogDescription>
          </DialogHeader>
          <ul className="space-y-3 text-sm text-muted-foreground">
            <li className="flex gap-3">
              <X className="mt-0.5 size-3.5 shrink-0 text-destructive" />
              Never rely on generated output for legal, financial, or HR decisions without review.
            </li>
            <li className="flex gap-3">
              <ShieldCheck className="mt-0.5 size-3.5 shrink-0 text-positive" />
              Transcripts and drafts stay on this device in the current prototype.
            </li>
            <li className="flex gap-3">
              <ShieldCheck className="mt-0.5 size-3.5 shrink-0 text-positive" />
              Attribution of action items is a suggestion — confirm owners before assigning work.
            </li>
          </ul>
        </DialogContent>
      </Dialog>
    </>
  );
}
